name: Quote Bot

on:
  schedule:
    - cron: '22 21 * * *'
  workflow_dispatch:

jobs:
  post:
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.24.6'

      - name: Install dependencies
        run: go mod tidy

      - name: Run Bot
        run: go run .
        env:
          CLIENT_ID: ${{ secrets.CLIENT_ID }}
          CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }}
          TOKEN_URL: https://application-auth.mixi.social/oauth2/token
          API_ADDRESS: application-api.mixi.social:443